# Generated by Django 2.2.16 on 2022-06-03 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_title_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='genres',
            new_name='genre',
        ),
    ]
