# Generated by Django 2.2.16 on 2022-06-06 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_auto_20220604_1419'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
